version: '3.8'

services:
  portfolio-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-frontend
    restart: unless-stopped
    ports:
      - "3080:80"
    networks:
      - portfolio-net

networks:
  portfolio-net:
    driver: bridge
